### ISSUE TITLE
Release version 1.10.0

### ISSUE THREAD

**Issue by jeffpaul** [tlovett1/safe-redirect-manager#222]
This issue is for tracking changes for the 1.10.0 release.  Target release date: **TBD**.

### Pre-release steps
- [x] review [open issues](https://github.com/10up/safe-redirect-manager/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.10.0) and either assign for PR or punt to the next release
- [x] review #215 and either refresh/merge or punt to the next release
- [x] review #218 and either refresh/merge or punt to the next release
- [x] review #220 and either refresh/merge or punt to the next release

### [Release steps](https://github.com/10up/safe-redirect-manager/blob/develop/CONTRIBUTING.md#release-instructions)
- [x] Branch: Starting from `develop`, cut a release branch named `release/1.10.0` for your changes.
- [x] Version bump: Bump the version number in `safe-redirect-manager.php` and `readme.txt` if it does not already reflect the version being released.
- [x] Changelog: Add/update the changelog in both `readme.txt` and `CHANGELOG.md`.
- [x] Props: Update `CREDITS.md` file with any new contributors, confirm maintainers are accurate.
- [x] Readme updates: Make any other readme changes as necessary.  `README.md` is geared toward GitHub and `readme.txt` contains WordPress.org-specific content.  The two are slightly different.
- [x] New files: Check to be sure any new files/paths that are unnecessary in the production version are included in `.gitattributes`.
- [x] Merge: Make a non-fast-forward merge from your release branch to `develop` (or merge the pull request), then do the same for `develop` into `trunk` (`git checkout trunk && git merge --no-ff develop`).  `trunk` contains the stable development version.
- [x] Test: While still on the `trunk` branch, test for functionality locally.
- [x] Push: Push your `trunk` branch to GitHub (e.g. `git push origin trunk`).
- [x] Release: Create a [new release](https://github.com/10up/safe-redirect-manager/releases/new), naming the tag and the release with the new version number, and targeting the `trunk` branch.  Paste the changelog from `CHANGELOG.md` into the body of the release and include a link to the closed issues on the milestone (e.g. `https://github.com/10up/safe-redirect-manager/milestone/10?closed=1`).
- [x] SVN: Wait for the [GitHub Action](https://github.com/10up/safe-redirect-manager/actions) to finish deploying to the WordPress.org repository.  If all goes well, users with SVN commit access for that plugin will receive an emailed diff of changes.
- [x] Check WordPress.org: Ensure that the changes are live on [https://wordpress.org/plugins/safe-redirect-manager/](https://wordpress.org/plugins/safe-redirect-manager/).  This may take a few minutes.
- [x] Close milestone: Edit the [1.10.0 milestone](https://github.com/10up/safe-redirect-manager/milestone/10) with release date (in the `Due date (optional)` field) and link to GitHub release (in the `Description` field), then close the milestone.
- [x] Punt incomplete items: If any open issues or PRs which were milestoned for `1.10.0` do not make it into the release, update their milestone to `2.0.0` or `Future Release`.
